HEADER:
  label: "About me"

PRESENTATION:
  description: |
   As a dedicated professional specializing in artificial intelligence, machine learning, and computer vision, I hold a Master’s degree in Commercial Vehicle Technology from Rheinland-Pfälzische Technische Universität, 
   where I focused on driver assistance systems and automotive software development. My expertise includes systems engineering, Computer vision, and Machine Learning, with practical experience at Evomotiv GmbH developing advanced algorithms for monocular depth estimation using Python, ROS, and C++. My master’s thesis on panoptic segmentation for autonomous driving underscores my ability to optimize AI systems for real-time applications. I am passionate about driving digital transformation and innovation in dependable AI, digital twins, and system modernization. 
   Proficient in German (B1) and English, I excel in interdisciplinary collaboration and effective communication. Let's connect to explore opportunities for creating advanced, sustainable technological solutions.

DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "Image processing"
      icon: "config/assets/icons/mobile.svg"
      description: "Development of algorithms for perception stack."
    - title: "Scripting"
      icon: "config/assets/icons/code.svg"
      description: "Automation and task scripting using Python to enhance efficiency and productivity."
    - title: "Data Science"
      icon: "config/assets/icons/compass.svg"
      description: "Deploy ETL pipelines into cloud"
    - title: "Web Development"
      icon: "config/assets/icons/laptop-code.svg"
      description: "High-quality development of sites at the professional level."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "Git"
      icon: "config/assets/icons/git.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "MongoDB"
      icon: "config/assets/icons/mongodb.svg"
    - title: "HTML"
      icon: "config/assets/icons/html.svg"
    - title: "AI"
      icon: "config/assets/icons/ai.svg"
    - title: "Jupyter"
      icon: "config/assets/icons/jupyter.svg"
    - title: "Linux"
      icon: "config/assets/icons/linux.svg"
