HEADER:
  label: "Contact"

LOCATION:
  embed: "https://www.google.com/maps/place/Kurt-Schumacher-Stra%C3%9Fe,+67663+Kaiserslautern/@49.4246275,7.7398723,740m/data=!3m2!1e3!4b1!4m6!3m5!1s0x47966d5746d511cd:0x6d9ad873f8eaa0bf!8m2!3d49.424624!4d7.7424472!16s%2Fg%2F1vd940h2!5m1!1e2?entry=ttu&g_ep=EgoyMDI1MDMzMC4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D"

FORM:
  label: "Contact Form"
  fields:
    - name: "Koushik Samudrala"
    - email: "koushiksamudrala111@gmail.com"
    - message: "Your message"
    - submit: "Send message"
