# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Software Developer"
  name: "Koushik Samudrala"
  username: "KoushikSamudrala" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "koushiksamudrala111@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+49 17676989480"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "December 14, 1995"
    icon: "calendar-outline"
  - label: "Location"
    value: "Kaiserslautern, Germany"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/koushik-samudrala-4372b892/"
  - icon: "logo-github"
    url: "https://github.com/KoushikSamudrala"

